# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='completed',
            new_name='complted',
        ),
    ]
