# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20171130_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='complted',
            new_name='completed',
        ),
    ]
